### ISSUE TITLE
Backlight not working

### ISSUE THREAD

**Issue by ghost** [Baio1977/HP-250-G6-Kabylake#3]
after installation i realized that brightness isn't working
i tried to reinstall the EFI folder but that didnt fix anything
ill try to find a way to fix it myself for now
macOS ver: 11.7.10, Intel HD Graphics 620 1536 MB

![Screen Shot 2024-01-20 at 14 09 52](https://github.com/Baio1977/HP-250-G6-Kabylake/assets/157216002/6b00ee4d-27ee-4a85-b359-5f7012809ae0)

**Comment by ghost** [comment]
i found a fix, i used Code instead of Releases and theres newer files too.

**Comment by Baio1977** [comment]
https://github.com/Baio1977/HP-250-G6-Kabylake/releases/tag/V3
Can you test this EFI???
Let me know if everything works here.
Thank you

**Comment by ghost** [comment]
yeah everything works _including bluetooth_ and etc
thanks
